// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB1wrWOhKvomyBC68xbsKOp6bXcfopSbDk',
    appId: '1:275745510969:web:a78de6c529e06e9ce05fe8',
    messagingSenderId: '275745510969',
    projectId: 'edify-26929',
    authDomain: 'edify-26929.firebaseapp.com',
    storageBucket: 'edify-26929.firebasestorage.app',
    databaseURL: 'https://edify-26929-default-rtdb.firebaseio.com/'
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAxpBuTVTwdrGN47tIeA-47WHlc2VnN5cc',
    appId: '1:275745510969:android:5cb1184432eb77d2e05fe8',
    messagingSenderId: '275745510969',
    projectId: 'edify-26929',
    storageBucket: 'edify-26929.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDh5EjgYfAthOghluNllSmK1JYIKdupX5Q',
    appId: '1:275745510969:ios:8c6f1a4b2e99aa8ae05fe8',
    messagingSenderId: '275745510969',
    projectId: 'edify-26929',
    storageBucket: 'edify-26929.firebasestorage.app',
    iosBundleId: 'com.example.edify',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDh5EjgYfAthOghluNllSmK1JYIKdupX5Q',
    appId: '1:275745510969:ios:8c6f1a4b2e99aa8ae05fe8',
    messagingSenderId: '275745510969',
    projectId: 'edify-26929',
    storageBucket: 'edify-26929.firebasestorage.app',
    iosBundleId: 'com.example.edify',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyB1wrWOhKvomyBC68xbsKOp6bXcfopSbDk',
    appId: '1:275745510969:web:b8e1f66f8aad30e5e05fe8',
    messagingSenderId: '275745510969',
    projectId: 'edify-26929',
    authDomain: 'edify-26929.firebaseapp.com',
    storageBucket: 'edify-26929.firebasestorage.app',
  );
}
